---
abstract: 'Plack Server implementation for POE'
author:
  - 'Paul Driver, C<< <frodwith at cpan.org> >>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-Server-POE
no_index:
  directory:
    - inc
    - t
requires:
  HTTP::Message::PSGI: 0
  HTTP::Status: 0
  POE: 0
  POE::Component::Server::TCP: 0
  POE::Filter::HTTP::Parser: 0
  Plack: 0
  perl: 5.8.8
resources:
  license: http://dev.perl.org/licenses/
version: 0.4
